
fun main() {
    val post1 =  Post(1,
        5,
        1,
        12,
        1,
        "1",
        1,
        1,
        1,
        2,
        1,
        5,
        1,
        2,
        "post",
        postSource = PostSource("1","1","1","1"),
        attachments = Photo(1,2,3,"1",1),
        geo = Geo("1","1","1"),
        1,
        null,
        true,
        true,
        true,
        1,
        true,
        true,
        donut = Donut(true,2,true,true,"5"),
        1
    )

    val post2 =  Post(1,
        5,
        1,
        12,
        1,
        "1",
        1,
        1,
        1,
        2,
        1,
        5,
        1,
        2,
        "post",
        postSource = PostSource("1","1","1","1"),
        attachments = Link(1,1,"2","1","1"),
        geo = Geo("1","1","1"),
        1,
        null,
        true,
        true,
        true,
        1,
        true,
        true,
        donut = Donut(true,2,true,true,"5"),
        1
    )
}

