data class Post (
    val id: Int,
    val ownerId: Int,
    val fromId: Int,
    val createdBy: Int,
    val date: Int,
    val text: String?,
    val replyOwnerId: Int,
    val replyPostId: Int,
    val friendsOnly: Int?,
    val comments: Int = 0,
    val copyright: Int,
    val likes: Int = 0,
    val reposts: Int,
    val views: Int,
    val postType: String,
    val postSource: PostSource?,
    val attachments: Attachment?,
    val geo: Geo?,
    val signerId: Int,
    val copyHistory: Array <PostSource>?,
    val canPin: Boolean,
    val canDelete: Boolean,
    val canEdit: Boolean,
    val isPinned: Int?,
    val markedAsAds: Boolean,
    val isFavorite: Boolean,
    val donut: Donut,
    val postponedId: Int
)